---

- name: Prepare
  hosts: molecule_hosts
  gather_facts: no
  become: yes
  tasks:
    - name: Setup LVM physical volume
      ansible.builtin.import_role:
        name: amtega.parted
      vars:
        parted_disks:
          - align: optimal
            device: /dev/sdb
            number: 1
            part_type: primary
            part_start: 0%
            part_end: 100%
            flags: [ lvm ]
            state: present

    - name: Setup LVM volume group
      ansible.builtin.import_role:
        name: amtega.lvm_vg
      vars:
        lvm_vg:
          - vg: vgtesting
            pvs: /dev/sdb1
            pesize: "4"
            state: present

    - name: Setup LVM logical volume
      ansible.builtin.import_role:
        name: amtega.lvm_lv
      vars:
        lvm_lv:
          - vg: vgtesting
            lv: lvtest
            size: 512M
